name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull image
      run: docker image pull richardbronosky/latex-compiler
    - name: Clean
      run: make clean
    - name: Build PDF
      run: make
    - name: Store PDF
      uses: actions/upload-artifact@v4
      with:
        name: b_luchen_resume.pdf
        path: b_luchen_resume.pdf
